### ISSUE TITLE
Consistency issues

### ISSUE THREAD

**Issue by xacrimon** [Gregory-Meyer/cht#6]
With the current implementation of get_bucket it looks like it can swing in the next BucketArray mid resize, this may be an issue because values may appear to temporarily not appear in the map. This may happen if the array is switched without all values moved.

**Comment by Gregory-Meyer** [comment]
This might be something I fixed in [read-modify-write](https://github.com/Gregory-Meyer/cht/tree/read-modify-write) before discovering that there's a double free bug hanging around somewhere. Specifically, I think I fixed what you're talking about in 875ab35.

**Comment by Gregory-Meyer** [comment]
Closed by #9
