### ISSUE TITLE
support upsert and remove_if

### ISSUE THREAD

**Issue by Future2100** [Gregory-Meyer/cht#7]
1. upsert
    update value when it existed or just insert

2. remove_if:
    remove only when the condition is matched

**Comment by Gregory-Meyer** [comment]
OK, you get upsert with #9 and #8 in the form of `insert_or_modify`.

**Comment by Future2100** [comment]
Ok, I am also looking forward to getting remove_if ASAP.

**Comment by Gregory-Meyer** [comment]
FYI -- don't use cht for anything you value right now. There's a double-free bug somewhere when concurrently growing the hash table.

**Comment by Gregory-Meyer** [comment]
What's your usecase for a `remove_if` function? Not sure what it provides over `if f() { map.remove(key); }`

**Comment by Future2100** [comment]
I have the value that is a list, I want to remove it when it is empty.
